name: build
on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - name: consistent generated code
      run: ./generate.sh && (git status | grep 'working tree clean')
    - name: spotless
      run: gradle spotlessCheck

  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - name: build & test
      run: gradle test
    - name: check Java 8 targeting
      run: |
        javap -verbose build/classes/java/main/net/mlin/iitj/DoubleIntervalTree.class | grep 'major version: 52'
    - name: docs
      run: gradle docs
    - name: mvn-repo
      run: gradle publish
